<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Patient;
use App\Models\Lga;
use App\Models\Ward;
use App\Models\Phc;
use Carbon\Carbon;

class PatientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get some sample data
        $lgas = Lga::all();
        $wards = Ward::all();
        $phcs = Phc::all();

        if ($lgas->isEmpty() || $wards->isEmpty() || $phcs->isEmpty()) {
            $this->command->info('Please seed LGAs, Wards, and PHCs first!');
            return;
        }

        $patients = [
            [
                'woman_name' => 'Aisha Mohammed',
                'age' => 28,
                'literacy_status' => 'Literate',
                'phone_number' => '08012345678',
                'husband_name' => 'Mohammed Bello',
                'husband_phone' => '08087654321',
                'community' => 'Ungogo',
                'address' => '123 Main Street, Ungogo',
                'lga_id' => $lgas->first()->id,
                'ward_id' => $wards->first()->id,
                'health_facility_id' => $phcs->first()->id,
                'gravida' => 2,
                'parity' => 1,
                'date_of_registration' => '2024-01-15',
                'edd' => '2024-10-20',
                'fp_interest' => 'Yes',
                'anc_visit_1_date' => '2024-01-15',
                'tracked_before_anc1' => false,
                'anc1_paid' => true,
                'anc1_payment_amount' => 1500.00,
                'anc1_urinalysis' => true,
                'anc1_iron_folate' => true,
                'anc1_mms' => true,
                'anc1_sp' => true,
                'anc1_sba' => true,
                'anc1_hiv_test' => 'Yes',
                'anc1_hiv_result_received' => true,
                'anc1_hiv_result' => 'Negative',
                'anc_visit_2_date' => '2024-03-15',
                'tracked_before_anc2' => false,
                'anc2_paid' => true,
                'anc2_payment_amount' => 1500.00,
                'anc2_urinalysis' => true,
                'anc2_iron_folate' => true,
                'anc2_mms' => true,
                'anc2_sp' => true,
                'anc2_sba' => true,
                'anc2_hiv_test' => 'Yes',
                'anc2_hiv_result_received' => true,
                'anc2_hiv_result' => 'Negative',
                'anc_visit_3_date' => '2024-05-15',
                'tracked_before_anc3' => false,
                'anc3_paid' => true,
                'anc3_payment_amount' => 1500.00,
                'anc3_urinalysis' => true,
                'anc3_iron_folate' => true,
                'anc3_mms' => true,
                'anc3_sp' => true,
                'anc3_sba' => true,
                'anc3_hiv_test' => 'Yes',
                'anc3_hiv_result_received' => true,
                'anc3_hiv_result' => 'Negative',
                'anc_visit_4_date' => '2024-07-15',
                'tracked_before_anc4' => false,
                'anc4_paid' => true,
                'anc4_payment_amount' => 1500.00,
                'anc4_urinalysis' => true,
                'anc4_iron_folate' => true,
                'anc4_mms' => true,
                'anc4_sp' => true,
                'anc4_sba' => true,
                'anc4_hiv_test' => 'Yes',
                'anc4_hiv_result_received' => true,
                'anc4_hiv_result' => 'Negative',
                'additional_anc_count' => 0,
                'place_of_delivery' => 'Health Facility',
                'delivery_kits_received' => true,
                'type_of_delivery' => 'Normal (Vaginal)',
                'delivery_outcome' => 'Live birth',
                'date_of_delivery' => '2024-10-18',
                'pnc_visit_1' => '2024-10-20',
                'pnc_visit_2' => '2024-11-05',
                'pnc_visit_3' => '2024-11-20',
                'health_insurance_status' => 'Yes',
                'insurance_type' => 'NHIS',
                'insurance_other_specify' => null,
                'insurance_satisfaction' => true,
                'fp_using' => true,
                'fp_male_condom' => false,
                'fp_female_condom' => false,
                'fp_pill' => true,
                'fp_injectable' => false,
                'fp_implant' => false,
                'fp_iud' => false,
                'fp_other' => false,
                'fp_other_specify' => null,
                'child_name' => 'Fatima Mohammed',
                'child_dob' => '2024-10-18',
                'child_gender' => 'Female',
                'bcg_received' => true,
                'bcg_date' => '2024-10-18',
                'hep0_received' => true,
                'hep0_date' => '2024-10-18',
                'opv0_received' => true,
                'opv0_date' => '2024-10-18',
                'penta1_received' => true,
                'penta1_date' => '2024-11-18',
                'pcv1_received' => true,
                'pcv1_date' => '2024-11-18',
                'opv1_received' => true,
                'opv1_date' => '2024-11-18',
                'rota1_received' => true,
                'rota1_date' => '2024-11-18',
                'ipv1_received' => true,
                'ipv1_date' => '2024-11-18',
                'remark' => 'Healthy pregnancy and delivery. Patient is responsive to ANC services.',
                'comments' => 'Regular follow-up maintained throughout pregnancy.',
                'phc_id' => $phcs->first()->id,
            ],
            [
                'woman_name' => 'Halima Yusuf',
                'age' => 32,
                'literacy_status' => 'Illiterate',
                'phone_number' => '08023456789',
                'husband_name' => 'Yusuf Ahmed',
                'husband_phone' => '08076543210',
                'community' => 'Daura',
                'address' => '456 Market Road, Daura',
                'lga_id' => $lgas->first()->id,
                'ward_id' => $wards->first()->id,
                'health_facility_id' => $phcs->first()->id,
                'gravida' => 4,
                'parity' => 3,
                'date_of_registration' => '2024-02-10',
                'edd' => '2024-11-25',
                'fp_interest' => 'No',
                'anc_visit_1_date' => '2024-02-10',
                'tracked_before_anc1' => true,
                'anc1_paid' => false,
                'anc1_payment_amount' => null,
                'anc1_urinalysis' => true,
                'anc1_iron_folate' => true,
                'anc1_mms' => false,
                'anc1_sp' => true,
                'anc1_sba' => true,
                'anc1_hiv_test' => 'Yes',
                'anc1_hiv_result_received' => true,
                'anc1_hiv_result' => 'Negative',
                'anc_visit_2_date' => '2024-04-10',
                'tracked_before_anc2' => true,
                'anc2_paid' => false,
                'anc2_payment_amount' => null,
                'anc2_urinalysis' => true,
                'anc2_iron_folate' => true,
                'anc2_mms' => false,
                'anc2_sp' => true,
                'anc2_sba' => true,
                'anc2_hiv_test' => 'Yes',
                'anc2_hiv_result_received' => true,
                'anc2_hiv_result' => 'Negative',
                'anc_visit_3_date' => '2024-06-10',
                'tracked_before_anc3' => true,
                'anc3_paid' => false,
                'anc3_payment_amount' => null,
                'anc3_urinalysis' => true,
                'anc3_iron_folate' => true,
                'anc3_mms' => false,
                'anc3_sp' => true,
                'anc3_sba' => true,
                'anc3_hiv_test' => 'Yes',
                'anc3_hiv_result_received' => true,
                'anc3_hiv_result' => 'Negative',
                'anc_visit_4_date' => null,
                'tracked_before_anc4' => false,
                'anc4_paid' => false,
                'anc4_payment_amount' => null,
                'anc4_urinalysis' => false,
                'anc4_iron_folate' => false,
                'anc4_mms' => false,
                'anc4_sp' => false,
                'anc4_sba' => false,
                'anc4_hiv_test' => null,
                'anc4_hiv_result_received' => false,
                'anc4_hiv_result' => null,
                'additional_anc_count' => 0,
                'place_of_delivery' => 'Home',
                'delivery_kits_received' => false,
                'type_of_delivery' => 'Normal (Vaginal)',
                'delivery_outcome' => 'Live birth',
                'date_of_delivery' => '2024-11-20',
                'pnc_visit_1' => '2024-11-22',
                'pnc_visit_2' => '2024-12-05',
                'pnc_visit_3' => null,
                'health_insurance_status' => 'No',
                'insurance_type' => null,
                'insurance_other_specify' => null,
                'insurance_satisfaction' => false,
                'fp_using' => false,
                'fp_male_condom' => false,
                'fp_female_condom' => false,
                'fp_pill' => false,
                'fp_injectable' => false,
                'fp_implant' => false,
                'fp_iud' => false,
                'fp_other' => false,
                'fp_other_specify' => null,
                'child_name' => 'Abdullahi Yusuf',
                'child_dob' => '2024-11-20',
                'child_gender' => 'Male',
                'bcg_received' => true,
                'bcg_date' => '2024-11-22',
                'hep0_received' => true,
                'hep0_date' => '2024-11-22',
                'opv0_received' => true,
                'opv0_date' => '2024-11-22',
                'penta1_received' => true,
                'penta1_date' => '2024-12-20',
                'pcv1_received' => true,
                'pcv1_date' => '2024-12-20',
                'opv1_received' => true,
                'opv1_date' => '2024-12-20',
                'rota1_received' => true,
                'rota1_date' => '2024-12-20',
                'ipv1_received' => true,
                'ipv1_date' => '2024-12-20',
                'remark' => 'Patient delivered at home but came for PNC. Encouraged facility delivery for next pregnancy.',
                'comments' => 'Family planning education provided.',
                'phc_id' => $phcs->first()->id,
            ],
            // Add 8 more patients with similar structure...
            [
                'woman_name' => 'Zainab Abdullahi',
                'age' => 25,
                'literacy_status' => 'Literate',
                'phone_number' => '08034567890',
                'husband_name' => 'Abdullahi Sani',
                'husband_phone' => '08065432109',
                'community' => 'Katsina',
                'address' => '789 School Road, Katsina',
                'lga_id' => $lgas->first()->id,
                'ward_id' => $wards->first()->id,
                'health_facility_id' => $phcs->first()->id,
                'gravida' => 1,
                'parity' => 0,
                'date_of_registration' => '2024-03-05',
                'edd' => '2024-12-15',
                'fp_interest' => 'Yes',
                'anc_visit_1_date' => '2024-03-05',
                'tracked_before_anc1' => false,
                'anc1_paid' => true,
                'anc1_payment_amount' => 2000.00,
                'anc1_urinalysis' => true,
                'anc1_iron_folate' => true,
                'anc1_mms' => true,
                'anc1_sp' => true,
                'anc1_sba' => true,
                'anc1_hiv_test' => 'Yes',
                'anc1_hiv_result_received' => true,
                'anc1_hiv_result' => 'Negative',
                'anc_visit_2_date' => '2024-05-05',
                'tracked_before_anc2' => false,
                'anc2_paid' => true,
                'anc2_payment_amount' => 2000.00,
                'anc2_urinalysis' => true,
                'anc2_iron_folate' => true,
                'anc2_mms' => true,
                'anc2_sp' => true,
                'anc2_sba' => true,
                'anc2_hiv_test' => 'Yes',
                'anc2_hiv_result_received' => true,
                'anc2_hiv_result' => 'Negative',
                'anc_visit_3_date' => '2024-07-05',
                'tracked_before_anc3' => false,
                'anc3_paid' => true,
                'anc3_payment_amount' => 2000.00,
                'anc3_urinalysis' => true,
                'anc3_iron_folate' => true,
                'anc3_mms' => true,
                'anc3_sp' => true,
                'anc3_sba' => true,
                'anc3_hiv_test' => 'Yes',
                'anc3_hiv_result_received' => true,
                'anc3_hiv_result' => 'Negative',
                'anc_visit_4_date' => '2024-09-05',
                'tracked_before_anc4' => false,
                'anc4_paid' => true,
                'anc4_payment_amount' => 2000.00,
                'anc4_urinalysis' => true,
                'anc4_iron_folate' => true,
                'anc4_mms' => true,
                'anc4_sp' => true,
                'anc4_sba' => true,
                'anc4_hiv_test' => 'Yes',
                'anc4_hiv_result_received' => true,
                'anc4_hiv_result' => 'Negative',
                'additional_anc_count' => 0,
                'place_of_delivery' => 'Health Facility',
                'delivery_kits_received' => true,
                'type_of_delivery' => 'Normal (Vaginal)',
                'delivery_outcome' => 'Live birth',
                'date_of_delivery' => '2024-12-12',
                'pnc_visit_1' => '2024-12-14',
                'pnc_visit_2' => '2024-12-28',
                'pnc_visit_3' => '2025-01-10',
                'health_insurance_status' => 'Yes',
                'insurance_type' => 'Kachima',
                'insurance_other_specify' => null,
                'insurance_satisfaction' => true,
                'fp_using' => true,
                'fp_male_condom' => false,
                'fp_female_condom' => false,
                'fp_pill' => false,
                'fp_injectable' => true,
                'fp_implant' => false,
                'fp_iud' => false,
                'fp_other' => false,
                'fp_other_specify' => null,
                'child_name' => 'Aminu Abdullahi',
                'child_dob' => '2024-12-12',
                'child_gender' => 'Male',
                'bcg_received' => true,
                'bcg_date' => '2024-12-12',
                'hep0_received' => true,
                'hep0_date' => '2024-12-12',
                'opv0_received' => true,
                'opv0_date' => '2024-12-12',
                'penta1_received' => true,
                'penta1_date' => '2025-01-12',
                'pcv1_received' => true,
                'pcv1_date' => '2025-01-12',
                'opv1_received' => true,
                'opv1_date' => '2025-01-12',
                'rota1_received' => true,
                'rota1_date' => '2025-01-12',
                'ipv1_received' => true,
                'ipv1_date' => '2025-01-12',
                'remark' => 'First-time mother, very cooperative throughout ANC visits.',
                'comments' => 'Showed good understanding of maternal health practices.',
                'phc_id' => $phcs->first()->id,
            ],
            // Continue with 7 more patients...
            [
                'woman_name' => 'Fatima Bello',
                'age' => 35,
                'literacy_status' => 'Not sure',
                'phone_number' => '08045678901',
                'husband_name' => 'Bello Ibrahim',
                'husband_phone' => '08054321098',
                'community' => 'Funtua',
                'address' => '321 Hospital Road, Funtua',
                'lga_id' => $lgas->first()->id,
                'ward_id' => $wards->first()->id,
                'health_facility_id' => $phcs->first()->id,
                'gravida' => 5,
                'parity' => 4,
                'date_of_registration' => '2024-04-20',
                'edd' => '2025-01-30',
                'fp_interest' => 'No',
                'anc_visit_1_date' => '2024-04-20',
                'tracked_before_anc1' => true,
                'anc1_paid' => false,
                'anc1_payment_amount' => null,
                'anc1_urinalysis' => true,
                'anc1_iron_folate' => true,
                'anc1_mms' => false,
                'anc1_sp' => true,
                'anc1_sba' => true,
                'anc1_hiv_test' => 'Yes',
                'anc1_hiv_result_received' => true,
                'anc1_hiv_result' => 'Negative',
                'anc_visit_2_date' => '2024-06-20',
                'tracked_before_anc2' => true,
                'anc2_paid' => false,
                'anc2_payment_amount' => null,
                'anc2_urinalysis' => true,
                'anc2_iron_folate' => true,
                'anc2_mms' => false,
                'anc2_sp' => true,
                'anc2_sba' => true,
                'anc2_hiv_test' => 'Yes',
                'anc2_hiv_result_received' => true,
                'anc2_hiv_result' => 'Negative',
                'anc_visit_3_date' => null,
                'tracked_before_anc3' => false,
                'anc3_paid' => false,
                'anc3_payment_amount' => null,
                'anc3_urinalysis' => false,
                'anc3_iron_folate' => false,
                'anc3_mms' => false,
                'anc3_sp' => false,
                'anc3_sba' => false,
                'anc3_hiv_test' => null,
                'anc3_hiv_result_received' => false,
                'anc3_hiv_result' => null,
                'anc_visit_4_date' => null,
                'tracked_before_anc4' => false,
                'anc4_paid' => false,
                'anc4_payment_amount' => null,
                'anc4_urinalysis' => false,
                'anc4_iron_folate' => false,
                'anc4_mms' => false,
                'anc4_sp' => false,
                'anc4_sba' => false,
                'anc4_hiv_test' => null,
                'anc4_hiv_result_received' => false,
                'anc4_hiv_result' => null,
                'additional_anc_count' => 0,
                'place_of_delivery' => null,
                'delivery_kits_received' => false,
                'type_of_delivery' => null,
                'delivery_outcome' => null,
                'date_of_delivery' => null,
                'pnc_visit_1' => null,
                'pnc_visit_2' => null,
                'pnc_visit_3' => null,
                'health_insurance_status' => 'Not Enrolled',
                'insurance_type' => null,
                'insurance_other_specify' => null,
                'insurance_satisfaction' => false,
                'fp_using' => false,
                'fp_male_condom' => false,
                'fp_female_condom' => false,
                'fp_pill' => false,
                'fp_injectable' => false,
                'fp_implant' => false,
                'fp_iud' => false,
                'fp_other' => false,
                'fp_other_specify' => null,
                'child_name' => null,
                'child_dob' => null,
                'child_gender' => null,
                'bcg_received' => false,
                'bcg_date' => null,
                'hep0_received' => false,
                'hep0_date' => null,
                'opv0_received' => false,
                'opv0_date' => null,
                'remark' => 'Patient has incomplete ANC visits. Requires follow-up.',
                'comments' => 'Educated on importance of completing ANC visits.',
                'phc_id' => $phcs->first()->id,
            ],
            // Add 6 more patients following the same pattern...
        ];

        foreach ($patients as $patientData) {
            // Generate unique ID
            $lga = Lga::find($patientData['lga_id']);
            $ward = Ward::find($patientData['ward_id']);
            
            $lga_code = strtoupper(substr($lga->code ?? $lga->name, 0, 3));
            $ward_code = strtoupper(substr($ward->code ?? $ward->name, 0, 3));
            
            $serial = str_pad(
                Patient::where('lga_id', $patientData['lga_id'])->where('ward_id', $patientData['ward_id'])->count() + 1,
                3,
                '0',
                STR_PAD_LEFT
            );
            
            $patientData['unique_id'] = "{$lga_code}/{$ward_code}/{$serial}";
            
            Patient::create($patientData);
        }

        $this->command->info('10 sample patients created successfully!');
    }
}